#!/bin/bash
#===========================================================================#
#   
#   Analyze - Digital Image Analysis for me
#
#   Workflow for applying an ImageJ macro for DIA of drydown images.
#   Currently supports:
#	- percent living (green) coverage)
#
#   Filename:	    anaDIAme
#   Version:	    1.0.0
#
#   Author:	    0cb - Christian Bowman
#   Creation:	    2019-08-20
#   Updated:	    2021-07-19 12:34
#   Project:	    "itwasme-DIA"; Digital Image Analysis
#
#   Usage:	    anaDIAme <project> <grass>
#
#--------------- Dependencies ---------------#
#   ImageJ/ FIJI
#
#===========================================================================#

#--------------- Changes ---------------#
# modified  2021-07-19	directories referenced
#
#--------------- Issues ---------------#
#
#
#--------------- Planned ---------------#
#
#

# inotify for automated changes in dirs
# mogrify -resize 50% *.JPG if size>3mb https://askubuntu.com/questions/1164/how-to-easily-resize-images-via-command-line

#--------------- vars ---------------#

CWDIR=$(pwd)
IMAGEJ=$HOME/programs/Fiji.app/ImageJ-linux64
#IJM=$HOME/gitrekt/itwasme-DIA/dryspell
LABDIR=$HOME/Lab_Baird/projects
#PCOV="/home/cb/Bioinf0cb/projects/fieldDIA/percent_coverage-DIA2.ijm"
#PCOV="/home/cb/bioprogs/projects/fieldDIA/percent_coverage-DIA.ijm"
PCOV="/home/cb/gitrekt/itwasme-DIA/dryspell/percent_coverage-DIA2.ijm"    #syntax requires full directory

STUDY=$1
GRASS=$2

#--------------- ImageJ macros ---------------#

#cd $LABDIR/$STUDY/$GRASS/DIA
echo $CWDIR

#$IMAGEJ --ij2 --headless --run $PCOV 'input="/home/cb/Baird_Lab/bermuda/Dry-down/Ratings2",output="/home/cb/Baird_Lab/bermuda/Dry-Down/Ratings2",suffix=".JPG"'

#commentblock
# S-v > :s/^/#

for dir in *;
#for dir in $LABDIR/$INPUT/Dry-down/Ratings2/;
do
    echo $dir
    
# __(2019-08-20 11:56)__ c[1] doesn't append the /Masks 
#    IJV='"'"input='"''"${c[0]}"''"',output='"''"${c[$1]}/Masks"''"',suffix=".JPG""'"'
#    IJV="'"'input="'""''"${c[0]}"''""'",output="'""''"${c[$1]}/Masks"''""'",suffix="'.JPG'"'"'"
    IJV="'"'input="'""''"${dir}"''""'",output="'""''"${dir}/Masks"''""'",suffix="'.JPG'"'"'"

    if [ -d "${dir}" ];
    then
	
	cd $dir

	#c[0]=$dir
	#c[1]=$dir/Masks
	
#	echo $dir
	echo ${dir}
#	echo $IJV
	echo ${IJV}
#	echo $IJV2

	# __(2019-08-20 10:43)__ percent coverage
	# imagej --ij2 --headless --run script 'input="dir1",output="dir1/Masks"'

	#$IMAGEJ --ij2 --headless --run $PCOV $(echo $IJV)
	echo "$IMAGEJ --ij2 --headless --run $PCOV ${IJV}" > $LABDIR/$STUDY/$GRASS/DIA/tmp.sh
	chmod 777 $LABDIR/$STUDY/$GRASS/DIA/tmp.sh
	cd $LABDIR/$STUDY/$GRASS/DIA && ./tmp.sh

	cd $dir/Masks
	for file in *.JPG;
	do
	    mv -- "$file" "${file%.JPG}.csv"
	done

	rm 15D*Start*.csv

	for meas in *.csv;
	do
	    awk 'FNR==2 {print $6}' $meas >> "$LABDIR/$STUDY/$GRASS/DIA/$dir-meas.csv"
	done
	
	cd $LABDIR/$STUDY/$GRASS/DIA

    fi

	# __(2019-08-20 10:43)__ percent green*
	
	
	# __(2019-08-20 10:47)__ DGCI*
	
	
	# __(2019-08-20 10:47)__ density*
	
    #fi
done

touch dia_full-$(date +%y_%m_%d).csv

for days in *-meas.csv;
do
    cat $days >> dia_full-$(date +%y_%m_%d).csv
done
    

